Добавляет header
htmlacademy-htmlcss/2056523-sedona-34 pull request #2
Opened 2022-05-25 18:15 UTC by Gri-F

Добавляет header

2022-05-27 11:36 UTC, Gri-F commented
Разметка всех страниц

2022-05-27 19:00 UTC, andreysgra requested changes

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +        <img class="logo" src="#" alt="Логотип Седона.">
Как правило, логотип сайта является ссылкой, которая ведёт на главную страницу. Оберните изображение ссылкой.

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +      <img class="logo" src="#" alt="Логотип Седона.">
Здесь тоже самое.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +              <a class="navigation-link" href="#">Гостиницы</a>
Значение `href` должно быть catalog.html.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +          <button class="custom-button" type="button">ХОЧУ СЮДА!</button>
Это не кнопка, а ссылка. Предполагается переход на другую страницу сайта.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +
Здесь и в остальных случаях: лишние пустые строки нужно убрать.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +                </div>
Здесь лучше использовать не `div`, а `p`.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +                    <img class="view-icon" src="#" alt="Список">
Это не изображения, а кнопки (`img` в разметку добавлять не нужно, так как это не контентные изображения).

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +                    <button class="price-button-favourites">В избранное</button>
Ссылки, а не кнопки.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +                      <img src="#" alt="Рейтинговая звезда">
В данном случае возможны 2 варианта разметки (кстати, это не рейтинг гостиницы, он есть в другом элементе, а её "звёздность"):
1. Так, как разметили вы, с помощью `img`, но тогда стоит использовать группу изображений, как в [этом](https://www.w3.org/WAI/tutorials/images/groups/) примере - `alt` заполняется только у первого изображения, а у остальных его значение пустое.
2. Используется фоновое изображение для блока `rating-stars`.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +                    <button class="price-button-favourites">В избранное</button>
```suggestion
                    <button class="price-button-favourites">В избранном</button>
```
Так как это другое состояние.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +      </section>
Зачем же здесь отдельная секция и другой список? Все гостиницы, которые показаны на странице - один общий список `catalog-list`.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +      <hr>
Этот тег для создания разделителя не нужен. Серая полоса делается средствами CSS (пока ничего не нужно делать).

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +          </li>
Вот эту всю нумерацию страниц замените на одну эту ссылку:
![image](https://user-images.githubusercontent.com/17790771/170771517-d48533a0-f610-401f-b909-3e380411d5ff.png)

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +          <p class="mailing">ПОДПИШИТЕСЬ НА РАССЫЛКУ</p>
Не нужно текст писать заглавными буквами.

2022-05-27 19:00 UTC, andreysgra commented on catalog.html
> +            <button>Подписаться</button>
Пропущен атрибут `type`.

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +          <img class="presentation-picture-style" src="#" alt="Фон.">
Разделять изображение на несколько отдельных не нужно. Это одно целое изображение:
![image](https://user-images.githubusercontent.com/17790771/170650716-0f81acf7-293e-4135-bca0-7a6272b97e8b.png)
А фон гор - это другое изображение. Так как оно декоративное, то в разметке оно не нужно. [Как отличить контентное изображение от декоративного](https://up.htmlacademy.ru/htmlcss/34/module/2/item/19).

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +              <h2 class="real-town-title">НАСТОЯЩИЙ ГОРОДОК</h2>
Здесь и в остальных элементах списка не соблюдается иерархия заголовков. Критерий [HTML-02](https://up.htmlacademy.ru/htmlcss/34/criteries#HTML-02). Так как выше, в секции есть `h2`, то внутри списка стоит использовать `h3`.

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +          </li>
Этот блок
![image](https://user-images.githubusercontent.com/17790771/170199124-f8e42e26-a030-4034-bf6c-8776a68623c3.png)
нужно разметить отдельным списком, который будет вложенным в первый элемент списка `advantages-list`:
```
<ul class="advantages-list"
  <li class="advantages-item">
    <h3 class="advantages-item-title">Настоящий городок</h2>
    <p class="advantages-item-number">— №1 —</p>
    <p class="advantages-item-description">Седона — не аттракцион для туристов, там течет своя жизнь</p>
    <div class="advantages-item-picture">
       <img src="#" alt="Фоторафия городка.">
    </div>

    <ul>
      <li>
        <h4>Жильё</h3>
        <p>Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
      </li>
      <!-- ... -->
    </ul>
  </li>
  <!-- ... -->
</ul>
```

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +          </li>
Общее замечание по названию классов (касается не только этого блока, но и всего проекта в целом). Классы это CSS, а CSS нужно для оформления сайта. Давая название классу, нужно обращать внимание не только на контент, но и в немалой степени на оформление. Посмотрим на эти блоки:
![image](https://user-images.githubusercontent.com/17790771/170201148-281c9efb-02cd-4f19-a063-6c2fac1f61c3.png)
Внешний вид у них идентичен (если не считать небольших отличий в фоновом цвете), различается только содержимое. А так как CSS нужен для оформления, то названия классов у всех трёх блоков и классов элементов внутри них должны совпадать. Иначе вам для каждого блока придётся писать одни и те же стили.
Класс заголовка в первом блоке `class="housing-title"`, во втором `class="food-title"`. Блоки одинаковые внешне, заголовки одинаковые, а классы разные.

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +        <button class="hotel-search-button" type="button">ПОИСК ГОСТИНИЦЫ В СЕДОНЕ</button>
Ссылка, а не кнопка.

2022-05-27 19:00 UTC, andreysgra commented on index.html
> +            <button>Подписаться</button>
Не указан `type`.

2022-05-29 10:17 UTC, Gri-F reviewed
Исправления

2022-05-30 19:21 UTC, andreysgra approved these changes

2022-05-30 19:21 UTC, andreysgra commented on index.html
> +      <button class="custom-button" type="button">Хочу сюда!</button>
На странице каталога исправили на ссылку, а здесь забыли исправить.

2022-05-30 19:21 UTC, merged

2022-05-30 19:39 UTC, Gri-F commented on index.html
> +      <button class="custom-button" type="button">Хочу сюда!</button>
исправил