Базовая стилизация всех страниц
htmlacademy-htmlcss/2056523-sedona-34 pull request #4
Opened 2022-06-05 15:14 UTC by Gri-F

2022-06-06 14:23 UTC, andreysgra requested changes

2022-06-06 14:23 UTC, andreysgra commented on catalog.html
> +            <a class="breadcrumbs-link" href="index.html">Главная домик декор</a>
А вам не кажется, что текст ссылки нужно обернуть тегом `span` с классом `visually-hidden`? Текст будет скрытым.

2022-06-06 14:23 UTC, andreysgra commented on catalog.html
> +          </li>
А вот тут неверно. Вы сами, правильно определили, что это декорация. А за это элемент оформления, то ему **не место в разметке**. Ещё нужно понимать, что **список предназначен для объединения схожих по предназначению сущностей**. Это список ссылок, а декоративная стрелка ссылкой не является (задайтесь вопросом - если это ссылка, то на какую страницу она должна вести?).

2022-06-06 14:23 UTC, andreysgra commented on catalog.html
> +        </div>
Предыдущий вариант разметки у вас был правильным, зачем вы его переделали, непонятно.
1. Форма одна. Не нужно разбивать на две формы - чекбоксы в одной, а радиокнопки во второй.
2. Кнопки `submit`, `reset` должны находиться внутри тега `form`. Вне формы они не имеют смысла.

2022-06-06 14:23 UTC, andreysgra commented on catalog.html
> +              <img src="#" alt="Звезда">
1. Нет точки в конце описания в `alt`.
2. Текст "Звезда" не является информативным. Что за звезда? Звезда на небе, морская звезда, звезда Героя Советского Союза? А вот если вы напишите текст "Четырёхзвёздочный отель." то будет сразу понятно, что собой представляет это изображение.

Поправьте также в других карточках гостиниц.

2022-06-06 14:23 UTC, andreysgra commented on index.html
> +        <img class="presentation-picture-welcome" src="/images/welcome.png" width="458" height="352"
Ошибка в относительном пути к файлу (лишний слеш в начале). Браузер такое изображение не найдёт:
![image](https://user-images.githubusercontent.com/17790771/172176953-aaf3cb67-5619-4ef3-8e42-7137d65d0529.png)

2022-06-06 14:23 UTC, andreysgra commented on index.html
> +      <img class="divider-image" src="/images/divider.png" width="1200" height="57" alt="">
Это декоративное изображение и добавляется оно не через тег `img`, а средствами CSS, свойством `background-image`.

2022-06-06 14:23 UTC, andreysgra commented on index.html
>                <img class="inner-picture" src="#" alt="Картинка домика.">
Это всё декоративные изображения, то есть они добавляются средствами CSS.
![image](https://user-images.githubusercontent.com/17790771/172177846-15bd538e-3e27-4917-9865-1097fee48c87.png)

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +    width: 1200px;
`min-width`, а не `width`. Для `body` указываем минимально возможную ширину.

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +}
Свойства для этого класса неправильные. Сейчас, насколько помню, скрывать ничего не нужно. В следующих заданиях будет пояснение про этот класс и какие свойства ему нужны.

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +    background-image: url("/images/background/index-background.jpg");
Неверный путь к файлу. Про пути к файлам можно почитать здесь "[Абсолютные и относительные пути](https://up.htmlacademy.ru/htmlcss/34/book/2.3)".

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +    background-image: url("/images/background/mailing-background.jpg");
Неверный путь к файлу.

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +input[type="email"] {
Критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02).

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +    background: url("/images/background/catalog-background.jpg");
Неверный путь к файлу.

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +button[type="submit"] {
Критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02).

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +button[type="reset"] {
Критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02).

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +    background: #7DB54F;
Есть такой критерий [PROJ-01](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01). Конкретнее можно посмотреть [здесь](http://codeguide.academy/html-css.html#css-color-format).

И в целом присмотритесь к данному кодгайду, к его требованиям. Например, количество отступов, пустые строки и так далее. Критерий базовый, так что он важен.

2022-06-06 14:23 UTC, andreysgra commented on styles/style.css
> +input[type="email"] {
Критерий [CSS-02](https://up.htmlacademy.ru/htmlcss/34/criteries#CSS-02).

2022-06-08 18:44 UTC, andreysgra requested changes

2022-06-08 18:44 UTC, andreysgra commented on catalog.html
> +              <img src="/images/breadcrumbs-icon-house.svg" width="13" height="13" alt="Главная.">
Декоративное изображение. Есть базовый критерий [IMG-01](https://up.htmlacademy.ru/htmlcss/34/criteries#IMG-01) на этот счёт.

2022-06-08 18:44 UTC, andreysgra commented on catalog.html
> +          </li>
Декоративное изображение. Пояснение на этот счёт писал [здесь](https://github.com/htmlacademy-htmlcss/2056523-sedona-34/pull/4#discussion_r890174883).

2022-06-08 18:44 UTC, andreysgra commented on catalog.html
> +          <fieldset class="filter-groyp">
```suggestion
          <fieldset class="filter-group">
```

2022-06-08 18:44 UTC, andreysgra commented on catalog.html
> +          <fieldset class="filter-groyp">
```suggestion
          <fieldset class="filter-group">
```

2022-06-08 18:44 UTC, andreysgra commented on catalog.html
> +          <h2 class="visually-hidden">Выбор цены проживания.</h2>
В общем-то большого смысла в этом месте для заголовка нет.

2022-06-08 18:44 UTC, andreysgra commented on index.html
> +        <div class="diveder"></div>
Лишний элемент разметки. Не торопитесь добавлять теги. По ходу обучения станет понятно, как реализуется тот или иной элемент интерфейса или оформления.

2022-06-08 18:44 UTC, andreysgra commented on styles/style.css
> +    background: #82B3D3;
[http://codeguide.academy/html-css.html#css-color-format](http://codeguide.academy/html-css.html#css-color-format) - _Для записи использованы строчные буквы_. Местами у вас значение цвета записано правильно, строчными буквами, а местами неправильно. Это базовый критерий [PROJ-01](https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01) и он важен для успешной защиты.

2022-06-09 20:16 UTC, Gri-F commented
замечания справил

2022-06-10 18:21 UTC, andreysgra approved these changes

2022-06-10 18:21 UTC, andreysgra commented on catalog.html
>            </li>
[Здесь](https://github.com/htmlacademy-htmlcss/2056523-sedona-34/pull/4#discussion_r890174883), кроме прочего я писал _"Это элемент оформления, то **ему не место в разметке**."_ Обращал на это ваше внимание во второй проверке проекта. Почему не исправили, загадка.

2022-06-10 18:22 UTC, merged