Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2056523-sedona-34 pull request #5
Opened 2022-06-13 13:27 UTC by Gri-F

2022-06-14 05:58 UTC, andreysgra requested changes

2022-06-14 05:58 UTC, andreysgra commented on styles/style.css
> +}
Есть один важный момент, который стоит использовать при построении сетки в этом проекте. Как мы видим, в макете нет областей с фоновым цветом или фоновым изображением, которые упираются в края макета. Контентная область ограничена шириной 1200px, соответственно мы можем сделать один общий контейнер, в который поместить шапку, контентную область и подвал сайта:
```
<div class="page-container">
  <header class="main-header"></header>

  <main class="main-container"></main>

  <footer class="page-footer"></footer>
</div>
```

1. Это позволит не создавать три крупных контейнера контента, а обойтись одним.
2. В макете есть тень у этого слоя
![image](https://user-images.githubusercontent.com/17790771/173009225-29ea1693-844e-4465-bde7-b1e9b007d2e0.png)
Проще всего её применить к одному блоку, а не к трём разным.

2022-06-14 05:58 UTC, andreysgra commented on index.html
> +      <div class="page-container">
В этом месте контейнер `<div class="page-container">` не нужен. Как я писал в первом своём комментарии он будет общим для всей страницы сайта.

2022-06-14 05:58 UTC, andreysgra commented on catalog.html
> +      <div class="page-container">
Тоже самое и на странице каталога.

2022-06-14 05:58 UTC, andreysgra commented on catalog.html
> +                <span class="visually-hidden">Список</span>
Нет закрывающего тега `</button>`.
![image](https://user-images.githubusercontent.com/17790771/173503393-c66752ba-5c78-49af-8f84-c0b1ed02389b.png)

2022-06-15 12:38 UTC, Gri-F commented
исправил

2022-06-15 20:26 UTC, merged